# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3284e1dd23d43a8e11cb7380dd6f0e9b612bef7e52959ddcce13b50ca5b7e4f0a2397c2ba51a1c751688aa50dd946d41059596070df45e6136fd48304eb68d2

test:
  secret_key_base: bfad1ec4b135cd800b3093958aba4eddbc4cd861f982f6f7ba8cd26e3f9eb6b898c5d4b0445a32ae051eda692e023c44f341ce5c272efc3f8da6ef213fcad241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
