# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c80d3d60cc588a5a3b29d7dd3e959f69cbfc9b45858b4d71775e8f70cf66c37791f2faca753033bc560064add51c598e07c74cd6c4f451abaa4d0ec82f32038c

test:
  secret_key_base: 318fbd0b6d1d520c39bbcb0878de09f7455b46f5548e49578697546a57fa049ee63588aed83ee292905f59cb17da571f6d27f8a2f940ac74877f1ecd41d6e850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
