# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 119c10ff6c34982d2914c4bcc4748de0fea76c25c4480fd65cb449e1be576024cc1d0c231fdd627171b9d6e2ee4d27cc2ac4e9d81115f09fe1aaa5488549b4df

test:
  secret_key_base: 79fbcbaeb87779c23206d17043295a0a48f1b4dde0c2c7a8890075ae4ae25f743a7b42f27784143507b47f9b6b5efc3c486c4e49afa31935cbd149597028639e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
