# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605d09b1edef665019a3e653056fe5cec288137b248454ebd98225258616e6ef65b7f6f9169f520afae26ea2c54bc52355e75e31f29c2f8d105356ac48deaf3b

test:
  secret_key_base: dab1025cecf5b336ebef373f98e7a132a5abc85ec2b8aab0a088c5581a0f5eb5c09984f4ab94cabdec08300b8c8e69a33f4a70d647772addebffad27bc1535c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
